//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KM
    {
        public string Magiovang { get; set; }
        public string Tengiovang { get; set; }
        public string Ngaytrongtuan { get; set; }
        public int Giobatdau { get; set; }
        public Nullable<int> Giokethuc { get; set; }
        public Nullable<int> Tileud { get; set; }
    }
}
