//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanbay
    {
        public string MaSb { get; set; }
        public string TenSb { get; set; }
        public string Diachi { get; set; }
    }
}
