//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuyenbay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chuyenbay()
        {
            this.CTchuyenbays = new HashSet<CTchuyenbay>();
            this.Hoadons = new HashSet<Hoadon>();
        }
    
        public string MaMB { get; set; }
        public string MaCB { get; set; }
        public Nullable<System.DateTime> Ngaybay { get; set; }
        public Nullable<System.TimeSpan> Thoigianbay { get; set; }
    
        public virtual Maybay Maybay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTchuyenbay> CTchuyenbays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoadon> Hoadons { get; set; }
    }
}
