//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTchuyenbay
    {
        public string MaCB { get; set; }
        public string MaTB { get; set; }
        public Nullable<System.TimeSpan> Thoigiandung { get; set; }
        public string SBtrunggian { get; set; }
    
        public virtual Chuyenbay Chuyenbay { get; set; }
        public virtual Tuyenbay Tuyenbay { get; set; }
        public virtual Sanbay Sanbay { get; set; }
    }
}
