//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTVe
    {
        public string MaHD { get; set; }
        public string Mave { get; set; }
        public Nullable<int> Soluongban { get; set; }
    
        public virtual Ve Ve { get; set; }
        public virtual Hoadon Hoadon { get; set; }
    }
}
